name: Drive to Parquet (TESTE 3 PDFs)

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      TZ: "America/Sao_Paulo"
      PYTHONUTF8: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: >
          python -m pip install --upgrade pip &&
          pip install pandas==2.* pdfplumber==0.* tqdm==4.* openpyxl==3.* pyarrow==17.* 
          google-api-python-client==2.* google-auth==2.* google-auth-httplib2==0.*

      - name: Compute RUN_TS (America/Sao_Paulo)
        run: echo "RUN_TS=$(TZ=America/Sao_Paulo date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV

      - name: Write sa.json (from secret)
        run: printf "%s" "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" > sa.json

      - name: Pull PDFs do Drive (TESTE: 3 arquivos)
        env:
          MAX_FILES: "3"
        run: |
          python scripts/drive_pull.py "${{ secrets.DRIVE_FOLDER_ID }}"
          echo "---- inbox ----"
          ls -lah inbox || true

      - name: Extrair e gerar Parquet+XLS (TESTE 3)
        env:
          PDF_DIR: inbox
          WRITE_SINGLE_RUN_PARQUET: "1"
          WRITE_XLS_ARTIFACT: "1"
          TZ_NAME: "America/Sao_Paulo"
          RUN_TS: ${{ env.RUN_TS }}
        run: |
          python scripts/PDF27.pyw --once --limit 3
          echo "---- data/ ----"; ls -lah data || true
          echo "---- out/  ----"; ls -lah out  || true

      - name: Upload XLS (artefato)
        uses: actions/upload-artifact@v4
        with:
          name: OFERTAS_XLS_${{ env.RUN_TS }}
          path: out/*.xlsx
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Parquets
        uses: actions/upload-artifact@v4
        with:
          name: OFERTAS_PARQUETS_${{ env.RUN_TS }}
          path: |
            data/*.parquet
            out/*.parquet
          if-no-files-found: warn
          retention-days: 7
