name: Merge Parquet (PR mode)

on:
  workflow_dispatch:
  push:
    paths:
      - "data/**/*.parquet"
      - "scripts/merge_parquet.py"
  schedule:
    - cron: "5 6 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow

      - name: Rodar merge
        run: |
          python scripts/merge_parquet.py \
            --data-dir data \
            --pattern "*.parquet" \
            --out data/ALL_MERGED.parquet

      - name: Criar PR com a atualização
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: atualizar data/ALL_MERGED.parquet [Actions]"
          title: "Atualizar ALL_MERGED.parquet"
          body: "Atualização automática do arquivo mestrado."
          branch: bot/update-merged-parquet
          delete-branch: true
          add-paths: |
            data/ALL_MERGED.parquet
